const BUSINESS={phone:'9708460980',email:'Crcaretaker@gmail.com'};
const verifiedScope={
  'Routine lawn mowing':'Choose a preferred time request. Routine mowing means mowing the lawn only.',
  'Trimming & edging':'Select this when you want trimming and edges cleaned up around the areas you identify.',
  'Seasonal cleanup':'Optional short-grass trimming plus removal of leaves, twigs, and weeds.',
  'Custom yard care':'Tell us what you need so we can confirm whether it fits the current setup: two mowers, a trimmer, weed puller, and edger.'
};
document.querySelectorAll('.service-card').forEach((card)=>{const title=card.querySelector('h3')?.textContent.trim();const copy=card.querySelector('p');if(title&&copy&&verifiedScope[title])copy.textContent=verifiedScope[title]});
document.querySelectorAll('.service-card h3').forEach((heading)=>{if(heading.textContent.trim()==='Seasonal cleanup')heading.textContent='Optional cleanup'});
const serviceFacts=document.querySelector('#service-facts');
document.querySelector('#services')?.after(serviceFacts);
if(serviceFacts){serviceFacts.innerHTML='<div class="setup-note"><span>Current setup</span><p>Two mowers, a trimmer, weed puller, and edger. Share the property details with your request so we can confirm the right scope.</p></div>';}
const requestNotes=document.querySelector('#service-notes');
if(requestNotes){requestNotes.innerHTML='<div class="section-heading"><div><p class="eyebrow"><span></span> Before you request</p><h2>Useful details,<br><em>without the guessing.</em></h2></div><p>Your selected day and window are a request, not a reserved appointment. We confirm the final scope and availability directly.</p></div><div class="facts-grid"><article><span>01</span><h3>Weather changes</h3><p>If conditions change, we confirm another option directly.</p></article><article><span>02</span><h3>Photo requests</h3><p>Photos stay on your device. Attach them manually after Messages or Mail opens.</p></article></div>';}
document.querySelectorAll('.service-icon').forEach((icon)=>icon.remove());
const photoHelper=document.querySelector('.photo-helper');
if(photoHelper)photoHelper.textContent='Photos stay on this device. After Messages or Mail opens, attach any photos manually.';
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-navigation');
const closeMenu=(focus=false)=>{toggle?.setAttribute('aria-expanded','false');toggle?.setAttribute('aria-label','Open menu');nav?.classList.remove('mobile-open');if(focus)toggle?.focus()};
toggle?.addEventListener('click',()=>{if(toggle.getAttribute('aria-expanded')==='true')return closeMenu(true);toggle.setAttribute('aria-expanded','true');toggle.setAttribute('aria-label','Close menu');nav?.classList.add('mobile-open')});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true')closeMenu(true)});
const photoInput=document.querySelector('#yard-photos'),photoPreview=document.querySelector('#photo-preview');photoInput?.addEventListener('change',()=>{photoPreview.innerHTML='';[...photoInput.files].slice(0,4).forEach(file=>{const img=document.createElement('img');img.alt=`Selected yard photo: ${file.name}`;img.src=URL.createObjectURL(file);photoPreview.append(img)})});
const preferredDate=document.querySelector('#preferred-date');if(preferredDate){const d=new Date();d.setDate(d.getDate()+1);const value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;preferredDate.min=value;preferredDate.value=value}
// Owner-editable planning assumptions; not a published rate card or final quote.
const ESTIMATE_CONFIG={minimum:35,base:30,lowRate:.007,highBase:42,highRate:.0085,trim:[8,12],cleanup:[15,25],mixed:[1.1,1.18],steep:[1.2,1.35]};
function planningRange(sqft,terrain,extras){let low=Math.max(ESTIMATE_CONFIG.minimum,Math.round(ESTIMATE_CONFIG.base+sqft*ESTIMATE_CONFIG.lowRate)),high=Math.max(low+10,Math.round(ESTIMATE_CONFIG.highBase+sqft*ESTIMATE_CONFIG.highRate));const f=terrain==='mixed'?ESTIMATE_CONFIG.mixed:terrain==='steep'?ESTIMATE_CONFIG.steep:null;if(f){low=Math.round(low*f[0]);high=Math.round(high*f[1])}if(extras.includes('Trimming & edging')){low+=8;high+=12}if(extras.includes('Leaf or debris cleanup')){low+=15;high+=25}return{low,high}}
const formatDate=value=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${value}T12:00:00`));
const bookingForm=document.querySelector('#booking-form'),requestResult=document.querySelector('#request-result');let requestText='';
bookingForm?.addEventListener('submit',()=>queueMicrotask(()=>{const text=document.querySelector('.text-request'),email=document.querySelector('.email-request');if(text)text.href=`sms:+1${BUSINESS.phone}?body=${encodeURIComponent(requestText)}`;if(email)email.href=`mailto:${BUSINESS.email}?subject=${encodeURIComponent('C.R. Caretaker visit request')}&body=${encodeURIComponent(requestText)}`;}));
if(requestResult){requestResult.setAttribute('aria-live','polite');const title=document.createElement('h3');title.className='result-title';title.tabIndex=-1;title.textContent='Your request is ready';requestResult.querySelector('.result-top')?.after(title)}
function addHandoff(){const actions=document.querySelector('.result-actions');if(!actions||actions.querySelector('.handoff-action'))return;[['Text this request','handoff-action',()=>`sms:+1${BUSINESS.phone}?body=${encodeURIComponent(requestText)}`],['Email this request','handoff-action handoff-email',()=>`mailto:${BUSINESS.email}?subject=${encodeURIComponent('C.R. Caretaker visit request')}&body=${encodeURIComponent(requestText)}`]].reverse().forEach(([label,cls,url])=>{const a=document.createElement('a');a.className=cls;a.textContent=label;a.href=url();a.addEventListener('click',()=>a.href=url());actions.prepend(a)})}
bookingForm?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('.form-error')?.remove();const data=new FormData(bookingForm),sqft=Number(data.get('sqft'));if(!Number.isFinite(sqft)||sqft<250||sqft>100000){const error=document.createElement('p');error.className='form-error';error.textContent='Enter the mowable grass area between 250 and 100,000 square feet. If you do not know it, text a photo and request a manual review.';bookingForm.prepend(error);bookingForm.querySelector('[name="sqft"]')?.focus();return}const service=data.get('service'),terrain=data.get('terrain'),extras=[data.get('trim')?'Trimming & edging':'',data.get('cleanup')?'Leaf or debris cleanup':''].filter(Boolean),date=data.get('date'),time=data.get('time'),range=planningRange(sqft,terrain,extras);document.querySelector('.result-price').textContent=`$${range.low}–$${range.high}`;document.querySelector('#result-copy').textContent=service!=='one-time'?'This is a one-time visit planning range. Ongoing-service pricing is confirmed separately after availability is reviewed.':'Planning range only. Grass height, access, gates, obstacles, slope, cleanup, and final scope can change the quote.';document.querySelector('#result-details').innerHTML=[`${sqft.toLocaleString()} sq ft`,service==='one-time'?'One-time visit':service==='weekly'?'Asked about weekly care':'Asked about every-other-week care',terrain==='flat'?'Mostly flat':terrain==='mixed'?'Some slope':'Steep / uneven',`Requested: ${formatDate(date)}, ${time}`,...extras].map(x=>`<span>${x}</span>`).join('');requestText=`C.R. Caretaker visit request\nService: ${service}\nLawn: ${sqft.toLocaleString()} sq ft\nTerrain: ${terrain}\nPreferred time: ${formatDate(date)}, ${time}${extras.length?`\nExtras: ${extras.join(', ')}`:''}\n\nThis is a request, not a confirmed booking.`;requestResult.hidden=false;addHandoff();requestResult.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});requestResult.querySelector('.result-title')?.focus()});
document.querySelector('.result-close')?.addEventListener('click',()=>requestResult.hidden=true);document.querySelector('.copy-estimate')?.addEventListener('click',async()=>{const s=document.querySelector('.copy-status');try{await navigator.clipboard.writeText(requestText);s.textContent='Request copied. You can also text or email it using the buttons above.'}catch{s.textContent='Copy is unavailable here. Use Text this request or Email this request.'}});
document.querySelector('.copy-contact')?.addEventListener('click',async()=>{const s=document.querySelector('.contact-copy-status');try{await navigator.clipboard.writeText(`C.R. Caretaker\nCall or text: 970 846 0980\nEmail: ${BUSINESS.email}`);s.textContent='Contact details copied.'}catch{s.textContent='Copy is unavailable here. Use the contact links.'}});document.querySelectorAll('.desktop-contact-values span').forEach(item=>{const strong=item.querySelector('strong');if(!strong)return;const raw=strong.textContent.trim(),a=document.createElement('a');a.href=raw.includes('@')?`mailto:${raw}`:`tel:+1${raw.replace(/\D/g,'')}`;a.textContent=raw;strong.replaceWith(a)});
